version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ".:/app"
    restart: always
    container_name: drf-uat
    ports:
      - "8000:8000"
    env_file:
      - .env.uat