version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             waitress-serve --port=8000 core.wsgi:application"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ".:/app"
    restart: always
    container_name: drf-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
