# Generated by Django 5.0.6 on 2024-06-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userlog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userlog",
            table="user_log",
        ),
    ]
