# Generated by Django 5.0.6 on 2024-06-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userlog",
            table="user_logs",
        ),
    ]
