# Generated by Django 5.0.6 on 2024-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_blacklistedaccesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklistedaccesstoken",
            name="token",
            field=models.TextField(),
        ),
    ]
